use std::{fmt::Write, sync::Arc};

use crate::{
    s3::{S3Client, split_s3_uri},
    statements::{
        copy::{CopyFormat, RedshqlCopy},
        create::{RedshqlCreateTable, TableKind},
    },
};
use arrow::{
    array::{
        Array, BinaryArray, BooleanArray, Date32Array, Decimal128Array, Float64Array, Int32Array,
        Int64Array, RecordBatch, StringArray, TimestampMicrosecondArray,
    },
    datatypes::DataType,
};
use bytes::Bytes;
use futures::{StreamExt, pin_mut, stream};
use parquet::arrow::arrow_reader::ParquetRecordBatchReaderBuilder;
use pgwire::{
    api::results::{DataRowEncoder, FieldFormat, FieldInfo, QueryResponse, Response, Tag},
    error::{PgWireError, PgWireResult},
};
use tokio_postgres::{
    Client as PgClient, GenericClient,
    binary_copy::BinaryCopyInWriter,
    types::{ToSql, Type as PgType},
};

use sqlparser::ast::DataType as SDataType;

pub async fn execute_select(sql: &str, pg: &PgClient) -> PgWireResult<Response> {
    let value = pg
        .client()
        .query_one_scalar::<i32, _>(sql, &[])
        .await
        .map_err(|e| PgWireError::ApiError(Box::new(e)))?;

    tracing::info!("Select executed");

    let schema = Arc::new(vec![FieldInfo::new(
        "column".into(),
        None,
        None,
        PgType::INT2,
        FieldFormat::Text,
    )]);

    let schema_ref = schema.clone();

    let row_stream = stream::iter(std::iter::once(value)).map(move |v| {
        let mut encoder = DataRowEncoder::new(schema_ref.clone());
        encoder.encode_field(&v)?;

        let r = encoder.take_row();

        Ok(r)
    });

    tracing::info!("Response built");

    Ok(Response::Query(QueryResponse::new(schema, row_stream)))
}

pub async fn execute_create_table(
    create: RedshqlCreateTable,
    pg: &PgClient,
) -> PgWireResult<Response> {
    let mut sql = String::from("");

    let create_kw = match create.table_kind {
        TableKind::Regular => "CREATE TABLE",
        TableKind::Temp => "CREATE TEMP TABLE",
        // Postgres accepts (and ignores) the LOCAL keyword per the SQL
        // standard, so this round-trips fine.
        TableKind::LocalTemp => "CREATE LOCAL TEMPORARY TABLE",
    };

    write!(sql, "{create_kw} ").unwrap();

    if create.if_not_exists {
        sql.push_str("IF NOT EXISTS ");
    }

    write!(sql, "{} (", create.table.to_string()).unwrap();

    let fields = create.columns.iter().fold(vec![], |mut acc, v| {
        let mut f = format!("{} {}", v.name, map_type(&v.data_type));

        if let Some(id) = &v.identity {
            f.push_str(&format!(
                " GENERATED BY DEFAULT AS IDENTITY (START WITH {} INCREMENT BY {})",
                id.seed, id.step
            ));
        } else if let Some(default) = &v.default {
            f.push_str(&format!(" DEFAULT {default}"));
        }

        if v.primary_key {
            f.push_str(" PRIMARY KEY");
        }

        if v.not_null {
            f.push_str(" NOT NULL");
        }

        if let Some(target) = &v.references {
            f.push_str(&format!(" REFERENCES {target}"));
        }

        acc.push(f);

        acc
    });

    let params = fields.join(", ");

    let sql = format!("{}{});", sql, params);

    tracing::info!("{}", &sql);

    let r = pg
        .execute(&sql, &[])
        .await
        .map_err(|e| PgWireError::ApiError(Box::new(e)))?;

    Ok(Response::Execution(
        Tag::new("create table").with_rows(r as usize),
    ))
}

pub async fn execute_s3_copy(copy: &RedshqlCopy, pg: &PgClient) -> anyhow::Result<usize> {
    let (bucket_name, prefix) = split_s3_uri(&copy.s3_uri)?;

    tracing::info!("Resolved source URI: s3://{}/{}", bucket_name, prefix);

    let s3_client = S3Client::new(&bucket_name).await?;

    tracing::info!("S3 client initialized");

    let mut failed_objects = 0usize;

    match &copy.format {
        CopyFormat::Parquet => {
            tracing::info!("Loading Parquet source");
            let columns = fetch_table_columns(pg, &copy.table.to_string()).await?;

            tracing::info!(
                "Target table '{}' {}",
                copy.table,
                if columns.is_some() {
                    "exists"
                } else {
                    "does not exist"
                }
            );

            let bytes = s3_client.get_object(&prefix).await?;

            tracing::info!("File '{}' read", prefix);

            let cols = if let Some(cols) = columns {
                cols
            } else {
                let bytes = s3_client.get_object(&prefix).await?;

                let reader = ParquetRecordBatchReaderBuilder::try_new(Bytes::from(bytes))?;

                tracing::info!("Parquet read from bytes");

                let fields: anyhow::Result<Vec<ColumnDef>> = reader
                    .schema()
                    .fields()
                    .iter()
                    .map(|v| {
                        Ok(ColumnDef {
                            name: v.name().into(),
                            pg_type: arrow_to_type(v.data_type())?,
                        })
                    })
                    .collect();

                tracing::info!("Fields collected from bytes");

                let fields = fields?;

                create_table(pg, &copy.table.to_string(), &fields).await?;

                fields
            };

            match load_one_object(pg, &copy.table.to_string(), &cols, bytes).await {
                Ok(n) => {
                    tracing::info!("{} records stored", n);
                }
                Err(e) => {
                    // Simplification vs real Redshift: MAXERROR there counts bad *rows*
                    // across the whole load; here each failed *file* counts as one error.
                    // Good enough for a test double where you're usually asserting
                    // "load either fully succeeds or trips MAXERROR", not exact counts.
                    failed_objects += 1;
                    eprintln!("[copy] error loading s3://{bucket_name}/{prefix}: {e:#}");
                    if failed_objects > copy.max_error as usize {
                        anyhow::bail!("MAXERROR ({}) exceeded", copy.max_error);
                    }
                }
            }
        }
        CopyFormat::Other(_) => {
            tracing::info!("Handling Multiple Parquet");
            let k = s3_client.list(&prefix).await?;

            // Handle the where table does not exist
            let cols = if let Some(first_k) = k.first() {
                let columns = fetch_table_columns(pg, &copy.table.to_string()).await?;

                let cols = if let Some(cols) = columns {
                    cols
                } else {
                    let bytes = s3_client.get_object(first_k).await?;

                    let reader = ParquetRecordBatchReaderBuilder::try_new(Bytes::from(bytes))?;

                    let fields: anyhow::Result<Vec<ColumnDef>> = reader
                        .schema()
                        .fields()
                        .iter()
                        .map(|v| {
                            Ok(ColumnDef {
                                name: v.name().into(),
                                pg_type: arrow_to_type(v.data_type())?,
                            })
                        })
                        .collect();

                    let fields = fields?;
                    create_table(pg, &copy.table.to_string(), &fields).await?;

                    fields
                };

                cols
            } else {
                vec![]
            };

            for key in k {
                let bytes = s3_client.get_object(&key).await?;

                match load_one_object(pg, &copy.table.to_string(), &cols, bytes).await {
                    Ok(n) => {
                        tracing::info!("{} records stored", n);
                    }
                    Err(e) => {
                        // Simplification vs real Redshift: MAXERROR there counts bad *rows*
                        // across the whole load; here each failed *file* counts as one error.
                        // Good enough for a test double where you're usually asserting
                        // "load either fully succeeds or trips MAXERROR", not exact counts.
                        failed_objects += 1;
                        eprintln!("[copy] error loading s3://{bucket_name}/{prefix}: {e:#}");
                        if failed_objects > copy.max_error as usize {
                            anyhow::bail!("MAXERROR ({}) exceeded", copy.max_error);
                        }
                    }
                }
            }
        }
        other => return Err(anyhow::anyhow!(format!("{:?} unsupported", other))),
    };
    Ok(1)
}

async fn fetch_table_columns(pg: &PgClient, table: &str) -> anyhow::Result<Option<Vec<ColumnDef>>> {
    let rows = pg
        .query(
            "SELECT column_name, udt_name FROM information_schema.columns \
         WHERE table_name = $1 ORDER BY ordinal_position",
            &[&table],
        )
        .await?;

    if rows.is_empty() {
        return Ok(None);
    }

    let rows: anyhow::Result<Vec<ColumnDef>> = rows
        .into_iter()
        .map(|row| {
            let name: String = row.get(0);
            let udt: String = row.get(1);
            Ok(ColumnDef {
                name,
                pg_type: udt_name_to_type(&udt)?,
            })
        })
        .collect();

    Ok(Some(rows?))
}

async fn create_table(pg: &PgClient, table: &str, columns: &[ColumnDef]) -> anyhow::Result<()> {
    let params = columns
        .iter()
        .fold(vec![], |mut acc, x| {
            let col = format!("{} {}", x.name.to_lowercase(), x.pg_type.name());
            acc.push(col);
            acc
        })
        .join(", ");

    let sql = format!("CREATE TABLE {} ({});", table, params);

    tracing::info!("{}", &sql);

    pg.client().execute(&sql, &[]).await?;

    Ok(())
}
async fn load_one_object(
    pg: &PgClient,
    table: &str,
    columns: &[ColumnDef],
    bytes: Vec<u8>,
) -> anyhow::Result<usize> {
    let reader = ParquetRecordBatchReaderBuilder::try_new(Bytes::from(bytes))?.build()?;

    let col_list = columns
        .iter()
        .map(|v| format!("\"{}\"", v.name))
        .collect::<Vec<String>>()
        .join(", ");
    let types = columns
        .iter()
        .map(|v| v.pg_type.clone())
        .collect::<Vec<PgType>>();

    let copy_sql = format!("COPY {table} ({col_list}) FROM STDIN BINARY");
    let sink = pg.copy_in(&copy_sql).await?;
    tracing::info!("COPY FROM STDIN started");
    let writer = BinaryCopyInWriter::new(sink, &types);

    pin_mut!(writer);

    let mut n = 0usize;

    for batch in reader {
        let batch = batch?;
        for row_idx in 0..batch.num_rows() {
            let row_values = extract_row(&batch, row_idx, columns)?;
            let refs: Vec<&(dyn ToSql + Sync)> = row_values
                .iter()
                .map(|v| v.as_ref() as &(dyn ToSql + Sync))
                .collect();

            writer.as_mut().write(&refs).await?;

            n += 1;
        }
    }

    writer.finish().await?;

    Ok(n)
}
struct ColumnDef {
    name: String,
    pg_type: PgType,
}

/// Only covers common scalar types. Extend as your Parquet exports need more —
/// this deliberately doesn't try to handle structs, lists, or decimals up front.
fn extract_row<'a>(
    batch: &'a RecordBatch,
    row: usize,
    columns: &'a [ColumnDef],
) -> anyhow::Result<Vec<Box<dyn ToSql + Send + Sync + 'a>>> {
    let mut out = Vec::with_capacity(columns.len());

    for (i, col) in columns.iter().enumerate() {
        let array = batch.column(i);
        let value: Box<dyn ToSql + Sync + Send> = match array.data_type() {
            DataType::Utf8 => {
                let a = array.as_any().downcast_ref::<StringArray>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<String>)
                } else {
                    Box::new(a.value(row).to_string())
                }
            }
            DataType::Int64 => {
                let a = array.as_any().downcast_ref::<Int64Array>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<i64>)
                } else {
                    Box::new(a.value(row))
                }
            }
            DataType::Int32 => {
                let a = array.as_any().downcast_ref::<Int32Array>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<i32>)
                } else {
                    Box::new(a.value(row))
                }
            }
            DataType::Float64 => {
                let a = array.as_any().downcast_ref::<Float64Array>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<f64>)
                } else {
                    Box::new(a.value(row))
                }
            }
            DataType::Decimal128(_, _) => {
                let a = array.as_any().downcast_ref::<Decimal128Array>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<f64>)
                } else {
                    Box::new(a.value(row) as f64)
                }
            }
            DataType::Binary => {
                let a = array.as_any().downcast_ref::<BinaryArray>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<Vec<u8>>)
                } else {
                    Box::new(a.value(row))
                }
            }
            DataType::Boolean => {
                let a = array.as_any().downcast_ref::<BooleanArray>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<bool>)
                } else {
                    Box::new(a.value(row))
                }
            }
            DataType::Date32 => {
                let a = array.as_any().downcast_ref::<Date32Array>().unwrap();
                if a.is_null(row) {
                    Box::new(None::<i32>)
                } else {
                    Box::new(a.value(row))
                }
            }
            DataType::Timestamp(_, _) => {
                let a = array
                    .as_any()
                    .downcast_ref::<TimestampMicrosecondArray>()
                    .unwrap();
                if a.is_null(row) {
                    Box::new(None::<i64>)
                } else {
                    Box::new(a.value(row))
                }
            }
            other => anyhow::bail!(
                "unsupported parquet column type {other:?} for column {}",
                col.name
            ),
        };
        out.push(value);
    }

    Ok(out)
}

fn udt_name_to_type(udt: &str) -> anyhow::Result<PgType> {
    Ok(match udt {
        "int2" => PgType::INT2,
        "int4" => PgType::INT4,
        "int8" => PgType::INT8,
        "float4" => PgType::FLOAT4,
        "float8" => PgType::FLOAT8,
        "numeric" => PgType::NUMERIC,
        "bool" => PgType::BOOL,
        "text" | "varchar" | "bpchar" => PgType::TEXT,
        "timestamp" => PgType::TIMESTAMP,
        "timestamptz" => PgType::TIMESTAMPTZ,
        "date" => PgType::DATE,
        "jsonb" => PgType::JSONB,
        other => anyhow::bail!("unsupported column type for COPY target: {other}"),
    })
}

fn arrow_to_type(a_type: &DataType) -> anyhow::Result<PgType> {
    match a_type {
        DataType::Boolean => Ok(PgType::BOOL),
        DataType::Binary | DataType::FixedSizeBinary(_) => Ok(PgType::BYTEA),
        DataType::Float64 => Ok(PgType::FLOAT8),
        DataType::Float32 | DataType::Float16 => Ok(PgType::FLOAT4),
        DataType::Int64 => Ok(PgType::INT8),
        DataType::Int32 => Ok(PgType::INT4),
        DataType::Decimal128(_, _) => Ok(PgType::NUMERIC),
        DataType::Utf8 => Ok(PgType::TEXT),
        DataType::Date32 => Ok(PgType::DATE),
        DataType::Timestamp(_, _) => Ok(PgType::TIMESTAMPTZ),
        other => Err(anyhow::anyhow!(format!("Unsuppoerted type: {}", other))),
    }
}

fn map_type(dt: &SDataType) -> String {
    match dt {
        // Redshift's SUPER (semi-structured) has no PG equivalent for
        // your emulator's purposes -> JSONB is the closest usable stand-in.
        SDataType::Custom(name, _) if name.to_string().eq_ignore_ascii_case("SUPER") => {
            "JSONB".to_string()
        }
        SDataType::Custom(name, mods) if name.to_string().eq_ignore_ascii_case("VARBYTE") => {
            match mods.first() {
                Some(len) => format!("BYTEA /* varbyte({len}) */"),
                None => "BYTEA".to_string(),
            }
        }
        SDataType::Custom(name, _) if name.to_string().eq_ignore_ascii_case("GEOMETRY") => {
            // Only meaningful if PostGIS is installed in the emulator image;
            // otherwise fall back to a bytea blob for round-tripping.
            "BYTEA /* geometry, requires postgis for real semantics */".to_string()
        }
        SDataType::Custom(name, _) if name.to_string().eq_ignore_ascii_case("HLLSKETCH") => {
            "BYTEA /* hllsketch */".to_string()
        }
        other => other.to_string(),
    }
}
